### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by reginato** [14tinchov/sphere-engine#1]
hi.
Im using your gem and, after add the api tokens, i run on console and return this message:

{"message"=>"Invalid API method.", "data"=>[], "error_code"=>0} 

i followed the this instructions:

client = SphereEngine::REST::Client.new do |config|
  config.access_token_compilers = "mytoken"
  config.access_token_problems  = "mytoken"
end

thants

**Comment by 14tinchov** [comment]
Hi @reginato  !

Recently Sphere Engine has changed its entire API, my gem stopped working, it would have to change the whole gem.

Maybe this week is working to integrate it into the new version

**Comment by reginato** [comment]
No problem man, i will study the API, maybe i can help you with this.
